function savetikz(fname, height)
	matlab2tikz(...
	    'filename', ['../figures/' fname '.tikz'], ...
	    'width', '\linewidth', 'height', height, ...
	    'extraTikzpictureOptions', {'trim axis left', 'trim axis right'});

end